# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.CharField(choices=[('a', '\u0422\u043e\u0432\u0430\u0440 \u0410'), ('b', '\u0422\u043e\u0432\u0430\u0440 B'), ('c', '\u0422\u043e\u0432\u0430\u0440 C'), ('d', '\u0422\u043e\u0432\u0430\u0440 D'), ('e', '\u0422\u043e\u0432\u0430\u0440 E')], max_length=200)),
                ('c_kg', models.IntegerField(default=0)),
            ],
        ),
    ]
