# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='good',
            field=models.CharField(choices=[('a', '\u0422\u043e\u0432\u0430\u0440 \u0410'), ('b', '\u0422\u043e\u0432\u0430\u0440 B'), ('c', '\u0422\u043e\u0432\u0430\u0440 C'), ('d', '\u0422\u043e\u0432\u0430\u0440 D'), ('e', '\u0422\u043e\u0432\u0430\u0440 E')], max_length=10),
        ),
    ]
