# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20160121_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='good',
        ),
        migrations.AddField(
            model_name='basket',
            name='good',
            field=models.ManyToManyField(to='price.Goods'),
        ),
    ]
