# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('capital', models.CharField(max_length=150)),
                ('currancy', models.CharField(blank=True, max_length=10, null=True)),
                ('pic', models.FileField(upload_to='country')),
            ],
        ),
    ]
