# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20151225_1250'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='country',
        ),
        migrations.AddField(
            model_name='blog',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='country.City'),
            preserve_default=False,
        ),
    ]
