# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('first meal', '\u041f\u0435\u0440\u0432\u043e\u0435 \u0431\u043b\u044e\u0434\u043e'), ('meat', '\u0411\u043b\u044e\u0434\u043e \u0438\u0437 \u043c\u044f\u0441\u0430'), ('fish', '\u0411\u043b\u044e\u0434\u043e \u0438\u0437 \u0440\u044b\u0431\u044b'), ('baked dishes', '\u0417\u0430\u043f\u0435\u0447\u0435\u043d\u043d\u044b\u0435 \u0431\u043b\u044e\u0434\u0430'), ('baking', '\u0412\u044b\u043f\u0435\u0447\u043a\u0430'), ('Dessert', '\u0414\u0435\u0441\u0435\u0440\u0442\u044b'), ('Other', '\u0414\u0440\u0443\u0433\u043e\u0435')], max_length=5)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('main_pic', models.FileField(upload_to='cuisine')),
                ('date_published', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
        ),
    ]
